### ISSUE TITLE
ISO download feature

### ISSUE THREAD

**Issue by the-anweddol-project** [the-anweddol-project/Anweddol-server#2]
# Concept

Having the possibility to download container ISO from a mirror URL via the CLI.

# Requirements

- A platform that can host a mirror as specified in the technical specifications [Container OS section](https://anweddol-server.readthedocs.io/en/latest/technical_specifications/core/virtualization.html#container-os), where the files would be programmatically accessible by their names (ex : *https://somedomain.com/mirror/anweddol_container.iso*).

# Examples

example 1 : 
*Example stub to get the remote ISO checksums*

```
import requests

CONTAINER_ISO_MIRROR_URL = "https://https://somedomain.com/mirror/"

MD5SUM_FILE_NAME = "md5sum.txt"
SHA256_FILE_NAME = "sha256.txt"

with requests.get(CONTAINER_ISO_MIRROR_URL + DEFAULT_MD5SUM_FILE_NAME) as req:
    remote_iso_md5 = req.content.decode()

with requests.get(CONTAINER_ISO_MIRROR_URL + DEFAULT_SHA256_FILE_NAME) as req:
    remote_iso_sha256 = req.content.decode()

print("Remote ISO MD5 : " + remote_iso_md5.split(" ")[0])
print("Remote ISO SHA256 : " + remote_iso_sha256.split(" ")[0])
```

example 2 : 
*Example `anwdlserver` command for using the feature*

```
anwdlserver dl-iso -u <container_iso_mirror_url>
```

**Comment by Darnethal0z** [comment]
This feature is cancelled for now, will re-open it if needed
